default: &default
  adapter: postgresql
  pool: 5
  t

development:
  <<: *default
  database:  rantly-development

test:
  <<: *default
  database:  rantly-test

production:
  <<: *default
  database: rantly_production
  username: rantly
  password: <%= ENV['RANTLY_DATABASE_PASSWORD'] %>


